"""add delivered status to messages

Revision ID: 8bbe10622c3d
Revises: cbaa6e8e3978
Create Date: 2025-06-26 16:58:37.617389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbe10622c3d'
down_revision: Union[str, Sequence[str], None] = 'cbaa6e8e3978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
