"""Add reset_otp and otp_timestamp to users

Revision ID: ee9555029bce
Revises: d6ae1f7a9706
Create Date: 2025-06-28 17:22:59.978363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9555029bce'
down_revision: Union[str, Sequence[str], None] = 'd6ae1f7a9706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_timestamp')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
